---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
   # Workaround: Perform npm install for node 8 and remove node_modules
    # This is required since package-lock.json is not commited to git
    - name: Analyze with NG SAST
      run: |
        npm install
        rm -rf node_modules
        rm -rf frontend/dist frontend/node_modules dist build     
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app juice-shop --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --js --cpg .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
   
  ## Uncomment the following section to enable build rule checking and enforcing.
  #Build-Rules: 
    #runs-on: ubuntu-latest
    #needs: NextGen-Static-Analysis
    #steps:
    #- uses: actions/checkout@v2
    #- name: Download ShiftLeft CLI
    #  run: |
    #    curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    #- name: Validate Build Rules
    #  run: |
    #    ${GITHUB_WORKSPACE}/sl check-analysis --app juice-shop \
    #       --source 'tag.branch=${{ github.event.pull_request.base.ref }}' \
    #       --target "tag.branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}" \
    #       --report \
    #       --github-pr-number=${{github.event.number}} \
    #       --github-pr-user=${{ github.repository_owner }} \
    #       --github-pr-repo=${{ github.event.repository.name }} \
    #       --github-token=${{ secrets.GITHUB_TOKEN }}
    #  env:
        #SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
